apiVersion: apps/v1
kind: Deployment
metadata:
 name: webapp
 labels:
   app: webapp
   type: front-end
spec:
  template:
    metadata:
      name: webapp-pod
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
        - name: webapp-pod
          image: ithelpstream/webapp:2.0.0
          volumeMounts:
           - name: webapp-volume
             mountPath: /opt 
      volumes:
       - name: webapp-volume
         persistentVolumeClaim:
           claimName: webapp-data
  replicas: 3
  selector:
    matchLabels:
      type: front-end
