apiVersion: apps/v1
kind: Deployment
metadata:
 name: webapp-qa
 labels:
   app: webapp-qa
   type: front-end
spec:
  template:
    metadata:
      name: webapp-qa
      labels:
        app: webapp-qa
        type: front-end
    spec:
      containers:
        - name: webapp-qa
          image: ithelpstream/webapp:2.0.0 
  replicas: 3
  selector:
    matchLabels:
      type: front-end
