apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: webapp-rs
 labels:
   app: webapp
   type: front-end
spec:
  template:
    metadata:
      name: webapp-pod
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
        - name: webapp-pod
          image: ithelpstream/webapp:2.0.0 
  replicas: 3
  selector:
    matchLabels:
      type: front-end
