apiVersion: v1
kind: Service
metadata: 
 name: webapp-service
spec: 
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
   #nodePort: 30008 #Node port range is 30000-32767
 selector:
  app: webapp
  type: front-end




