apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: web-application
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80
     port: 80
  selector:
   app: webapp
   type: front-end
